# Exported from Render on 2024-06-05T00:09:36Z
databases:
- name: djangohdp
  databaseName: djangohdp
  user: djangohdp_user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
services:
- type: web
  name: ERP-RRHH-HDP
  runtime: python
  repo: https://github.com/InfinityJaaR/RRHH-HDP
  plan: free
  envVars:
  - key: PYTHON_VERSION
    sync: false
  - key: DJANGO_SUPERUSER_USERNAME
    sync: false
  - key: DJANGO_SUPERUSER_PASSWORD
    sync: false
  - key: DJANGO_SUPERUSER_EMAIL
    sync: false
  - key: DATABASE_URL
    fromDatabase:
      name: djangohdp
      property: connectionString
  region: oregon
  buildCommand: ./build.sh
  startCommand: gunicorn ERPrrhh.wsgi
version: "1"
