# Generated by Django 5.0.2 on 2024-05-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0005_alter_asistencia_mes_asistencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permiso',
            name='fechasolicitud',
        ),
        migrations.AlterField(
            model_name='permiso',
            name='estado',
            field=models.CharField(choices=[('1', 'Aprobado'), ('2', 'Rechazado'), ('3', 'Pendiente')], default='Pendiente', max_length=10),
        ),
    ]
