# Generated by Django 5.0.2 on 2024-05-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0007_empleado_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.TextField(max_length=256),
        ),
    ]
