# Generated by Django 5.0.2 on 2024-05-31 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0011_alter_departamento_carnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='RRHH.departamento'),
        ),
    ]
