# Generated by Django 5.0.2 on 2024-06-01 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0015_remove_departamento_carnet_empleado_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='horas_trabajadas',
            new_name='horas_trabajadas_diunas',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='rol',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='horas_trabajadas_nocturnas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pago',
            name='asistencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='RRHH.asistencia'),
        ),
        migrations.AddField(
            model_name='pago',
            name='permiso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='RRHH.permiso'),
        ),
        migrations.CreateModel(
            name='auth_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.TextField(max_length=256)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='RRHH.empleado')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
