# Generated by Django 5.0.2 on 2024-06-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0016_rename_horas_trabajadas_asistencia_horas_trabajadas_diunas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Empleado')], default='2', max_length=1),
        ),
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
