# Generated by Django 5.0.2 on 2024-06-01 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0017_empleado_rol_delete_auth_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='permiso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='RRHH.permiso'),
        ),
    ]
