# Generated by Django 5.0.2 on 2024-05-31 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0002_remove_asistencia_horas_extras_nocturnas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='mes_asistencia',
            field=models.CharField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], default='Enero', max_length=2),
        ),
    ]
