# Generated by Django 5.0.2 on 2024-05-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0006_remove_permiso_fechasolicitud_alter_permiso_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Empleado')], default='2', max_length=1),
        ),
    ]
