# Generated by Django 5.0.2 on 2024-05-31 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0008_alter_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='encargados',
        ),
        migrations.AddField(
            model_name='area',
            name='encargado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_encargada', to='RRHH.empleado'),
        ),
    ]
