# Generated by Django 5.0.2 on 2024-05-31 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0010_alter_departamento_carnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='carnet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='RRHH.empleado'),
        ),
    ]
