# Generated by Django 5.0.2 on 2024-06-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0013_alter_municipio_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='descripcion_area',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descripcion_cargo',
            field=models.TextField(max_length=100),
        ),
    ]
