# Generated by Django 5.0.2 on 2024-06-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RRHH', '0019_empleado_telefono_alter_pago_fechapago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='permiso',
        ),
    ]
